
name: calendar metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
       - uses: lowlighter/metrics@latest
         name: Full-year calendar
         with:
              filename: metrics.plugin.isocalendar.fullyear.svg
              token: ${{ secrets.METRICS_TOKEN }}
              base: ""
              plugin_isocalendar: yes
              plugin_isocalendar_duration: full-year
