
name: lines metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
       - uses: lowlighter/metrics@latest
         name: Repositories and diff history

         with:
            filename: metrics.plugin.lines.history.svg
            token: ${{ secrets.METRICS_TOKEN }}
            base: ""
            plugin_lines: yes
            plugin_lines_sections: repositories, history
            plugin_lines_repositories_limit: 2
            plugin_lines_history_limit: 1
            repositories_skipped: |
              @use.patterns
              */*
              +lowlighter/metrics
