name: Waka Readme

on:
  schedule:
    # 12AM EST (midnight)
    - cron: '0 5 * * *'

jobs:
  update-readme:
    name: Update waka-readme-stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_LINES_OF_CODE: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_SHORT_INFO: "False"
#          SHOW_LOC_CHART: "True"
#          SHOW_LANGUAGE: "False"
#          SHOW_TIMEZONE: "False"
